services:
  # -----------------------------
  # 1. Remixフロントエンド (本番)
  # -----------------------------
  photoviewer_frontend:
    image: shunkicreate/photoviewer-frontend:latest
    container_name: photoviewer_frontend_container
    networks:
      - webnet
    environment:
      - PORT=${PORT}
      - BACKEND_API_ADDRESS=${BACKEND_API_ADDRESS}
      - NODE_ENV=production
    restart: always

  # -----------------------------
  # 2. Nginx (フロント用リバースプロキシ)
  # -----------------------------
  photoviewer_frontend_nginx:
    image: nginx:latest
    container_name: photoviewer_frontend_nginx_container
    depends_on:
      - photoviewer_frontend
    networks:
      - webnet
    environment:
      - PORT=${PORT}  # 必要に応じて
    ports:
      - "8081:81"     # 外部8081 → コンテナ内81ポート
    restart: always
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro

networks:
  webnet:
    external: true
