services:
  backend-prod:
    container_name: photo_viewer_backend_prod
    image: shunkicreate/photoviewer-backend:latest
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - NAS_SERVER_PATH=${NAS_SERVER_PATH}
      - NAS_SERVER_PORT=${NAS_SERVER_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
    networks:
      - webnet

networks:
  webnet:
    external: true
