# =========================
# Stage 1: builder
# =========================
FROM golang:1.23-alpine AS builder
ARG TARGETARCH=arm64

WORKDIR /app

# ソースコードをコピー
COPY . .

# Goモジュールのインストール
RUN go mod tidy

# ARM64 用にバイナリをビルド
RUN CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETARCH go build -o api-server ./cmd/server

# =========================
# Stage 2: runtime
# =========================
FROM alpine:latest

# ビルドしたバイナリをコピー
COPY --from=builder /app/api-server /api-server

# バイナリを実行
CMD ["/api-server"]
