apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoviewer-backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoviewer-backend
  template:
    metadata:
      labels:
        app: photoviewer-backend
    spec:
      containers:
      - name: photoviewer-backend
        image: shunkicreate/photoviewer-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: production
        - name: BACKEND_PORT
          valueFrom:
            secretKeyRef:
              name: backend-env-secret
              key: BACKEND_PORT
        - name: NAS_SERVER_PATH
          valueFrom:
            secretKeyRef:
              name: backend-env-secret
              key: NAS_SERVER_PATH
        - name: NAS_SERVER_PORT
          valueFrom:
            secretKeyRef:
              name: backend-env-secret
              key: NAS_SERVER_PORT
        resources:
          requests:
            cpu: "300m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
