apiVersion: v1
kind: Service
metadata:
  name: photoviewer-backend-svc
spec:
  selector:
    app: photoviewer-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
