apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoviewer-frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoviewer-frontend
  template:
    metadata:
      labels:
        app: photoviewer-frontend
    spec:
      containers:
      - name: photoviewer-frontend
        image: shunkicreate/photoviewer-frontendsha256:fee8e342ddf926b573014dfccc9de8d6201c5343655288b1017d0ce211b5e313
        ports:
          - containerPort: 3000
        env:
          - name: NODE_ENV
            value: "production"
          - name: BACKEND_API_ADDRESS
            valueFrom:
              secretKeyRef:
                name: front-env-secret
                key: BACKEND_API_ADDRESS
        envFrom:
          - secretRef:
              name: front-env-secret
        resources:
          requests:
            cpu: "300m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
