name: Build and push Docker image to Docker Hub

on:
  push:
    branches: [ "main" ]
  # ↑ main ブランチへ push されたときに実行
  # もし PR merge 時だけに限定したい場合は on: pull_request: ... など変更

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1) リポジトリのソースをチェックアウト
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2) Docker Hub にログイン
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3) Docker イメージをビルド＆プッシュ
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true  # ビルド後に push する
          tags: shunkicreate/photoviewer-backend:latest
          # ↑ ユーザー名/リポジトリ名:タグ
